/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aussie' at '11/3/16 9:15 AM' with Gradle 2.14.1
 *
 * @author Aussie, @date 11/3/16 9:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
